/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import scraper.Imdb_ator;
//import scraper.Scraper;

/**
 *
 * @author alex
 */
public class Frm_pesquisa extends javax.swing.JFrame {

    

    /**
     * Creates new form scraper_form
     */
    public Frm_pesquisa() {
        initComponents();
        // curso no textfield
        txt_criterio.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_grp_criterio = new javax.swing.ButtonGroup();
        pnl_pesquisa = new javax.swing.JPanel();
        txt_criterio = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        rad_ator = new javax.swing.JRadioButton();
        rad_filme = new javax.swing.JRadioButton();
        lbl_criterio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_resultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        pnl_pesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar por:"));
        pnl_pesquisa.setToolTipText("Search");
        pnl_pesquisa.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        txt_criterio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_criterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_criterioKeyPressed(evt);
            }
        });

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        btn_grp_criterio.add(rad_ator);
        rad_ator.setSelected(true);
        rad_ator.setText("Ator");
        rad_ator.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_atorItemStateChanged(evt);
            }
        });

        btn_grp_criterio.add(rad_filme);
        rad_filme.setText("Filme");
        rad_filme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_filmeItemStateChanged(evt);
            }
        });

        lbl_criterio.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_criterio.setText("Nome do ator:");

        javax.swing.GroupLayout pnl_pesquisaLayout = new javax.swing.GroupLayout(pnl_pesquisa);
        pnl_pesquisa.setLayout(pnl_pesquisaLayout);
        pnl_pesquisaLayout.setHorizontalGroup(
            pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad_filme)
                    .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                        .addComponent(rad_ator)
                        .addGap(44, 44, 44)
                        .addComponent(lbl_criterio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_criterio, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_pesquisar)
                .addContainerGap())
        );
        pnl_pesquisaLayout.setVerticalGroup(
            pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_criterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pesquisar)
                            .addComponent(lbl_criterio)))
                    .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                        .addComponent(rad_ator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rad_filme)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_resultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rad_filmeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_filmeItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Your selected code here.
            lbl_criterio.setText("Nome do filme:");
        }
    }//GEN-LAST:event_rad_filmeItemStateChanged

    private void rad_atorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_atorItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Your selected code here.
            lbl_criterio.setText("Nome do ator:");
        }
    }//GEN-LAST:event_rad_atorItemStateChanged

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        // o textbox está vazio?
        if (txt_criterio.getText().compareTo("") != 0) {
            //Qual radiobutton está selecionado
            if (rad_ator.isSelected()) {

                Imdb_ator scrap;
                scrap = busca_dados(txt_criterio.getText());
                limpa_tabela(tbl_resultado);
                nomeia_colunas_tabela(tbl_resultado, new Object[]{"FOTO", "ATOR", "LINK IMDB"});
                preenche_tabela(tbl_resultado, scrap);
            }
//            else if (rad_filme.isSelected()) {
//            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite algo para ser pesquisado!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private Imdb_ator busca_dados(String criterio) {
        //o construtor fará a pesquisa
        Imdb_ator scrap = new Imdb_ator(criterio);
        return scrap;
    }

    private void limpa_tabela(JTable tbl) {
        //model jtable
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        // atualizar tabela
        tbl.validate();
    }

    private void preenche_tabela(JTable tbl, Imdb_ator scrap) {
        //model jtable
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        //array objects
//        Object[] todos =  new Object[3];
        //put data in rows
        int i = 0;
        scrap.atores.forEach((item) -> {
//            model.addRow(item.toArray());
            try {
                URL url = new URL(item.get(0));
                BufferedImage image = ImageIO.read(url);
                ImageIcon icon = new ImageIcon(image);
//                todos.
                model.addRow(new Object[]{icon, item.get(1), item.get(2)});
            } catch (MalformedURLException ex) {
//                Logger.getLogger(Frm_pesquisa.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Erro:" + ex);
            } catch (IOException ex) {
//                Logger.getLogger(Frm_pesquisa.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Erro:" + ex);
            }
        });
        model.getColumnClass(0);
        model.getColumnClass(1);
        model.getColumnClass(2);
        tbl.setModel(model);
        tbl.validate();
        System.out.println("ColumnModel: " + tbl.getColumnModel());
    }

    private void nomeia_colunas_tabela(JTable tbl, Object[] nomes) {
        //model jtable
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setColumnIdentifiers(nomes);
        // atualizar tabela
        tbl.validate();
    }


    private void tbl_resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_resultadoMouseClicked

        int row = tbl_resultado.getSelectedRow(); //.rowAtPoint(evt.getPoint());
        int col = tbl_resultado.getSelectedColumn(); //.columnAtPoint(evt.getPoint());

        JOptionPane.showMessageDialog(null,
                "\nFoto: " + tbl_resultado.getValueAt(row, 0)
                + "\nAtor: " + tbl_resultado.getValueAt(row, 1)
                + "\nLink: " + tbl_resultado.getValueAt(row, 2),
                "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tbl_resultadoMouseClicked

    private void txt_criterioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_criterioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_pesquisar.doClick();
        }

    }//GEN-LAST:event_txt_criterioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_pesquisa frm = new Frm_pesquisa();
                frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_grp_criterio;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_criterio;
    private javax.swing.JPanel pnl_pesquisa;
    private javax.swing.JRadioButton rad_ator;
    private javax.swing.JRadioButton rad_filme;
    private javax.swing.JTable tbl_resultado;
    private javax.swing.JTextField txt_criterio;
    // End of variables declaration//GEN-END:variables
}
