/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import scraper.Imdb_ator;
import scraper.Scraper;

/**
 *
 * @author alex
 */
public class Frm_pesquisa extends javax.swing.JFrame {

    /**
     * Creates new form scraper_form
     */
    public Frm_pesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_grp_criterio = new javax.swing.ButtonGroup();
        pnl_pesquisa = new javax.swing.JPanel();
        txt_criterio = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        rad_ator = new javax.swing.JRadioButton();
        rad_filme = new javax.swing.JRadioButton();
        lbl_criterio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_resultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        pnl_pesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar por:"));
        pnl_pesquisa.setToolTipText("Search");
        pnl_pesquisa.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        btn_grp_criterio.add(rad_ator);
        rad_ator.setSelected(true);
        rad_ator.setText("Ator");
        rad_ator.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_atorItemStateChanged(evt);
            }
        });

        btn_grp_criterio.add(rad_filme);
        rad_filme.setText("Filme");
        rad_filme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_filmeItemStateChanged(evt);
            }
        });

        lbl_criterio.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_criterio.setText("Nome do ator:");

        javax.swing.GroupLayout pnl_pesquisaLayout = new javax.swing.GroupLayout(pnl_pesquisa);
        pnl_pesquisa.setLayout(pnl_pesquisaLayout);
        pnl_pesquisaLayout.setHorizontalGroup(
            pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad_filme)
                    .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                        .addComponent(rad_ator)
                        .addGap(44, 44, 44)
                        .addComponent(lbl_criterio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_criterio, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_pesquisar)
                .addContainerGap())
        );
        pnl_pesquisaLayout.setVerticalGroup(
            pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnl_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_criterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pesquisar)
                            .addComponent(lbl_criterio)))
                    .addGroup(pnl_pesquisaLayout.createSequentialGroup()
                        .addComponent(rad_ator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rad_filme)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_resultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rad_filmeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_filmeItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Your selected code here.
            lbl_criterio.setText("Nome do filme:");
        }
//        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
//            // Your deselected code here.
//        }
    }//GEN-LAST:event_rad_filmeItemStateChanged

    private void rad_atorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_atorItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Your selected code here.
            lbl_criterio.setText("Nome do ator:");
        }
    }//GEN-LAST:event_rad_atorItemStateChanged

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        // o textbox está vazio?
        if (txt_criterio.getText().compareTo("") != 0) {
            //Qual radiobutton está selecionado
            if (rad_ator.isSelected()) {
                //o construtor fará a pesquisa
                Imdb_ator scrap = new Imdb_ator(txt_criterio.getText());
                
                System.out.println(scrap.atores.get(0).get(0));
                //ppopular o jtable
                DefaultTableModel modelo = (DefaultTableModel)tbl_resultado.getModel();
                scrap.atores.forEach((item) -> {
                    modelo.addRow(item.toArray());
                });
                

            } else if (rad_filme.isSelected()) {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite algo para ser pesquisado!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void tbl_resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_resultadoMouseClicked

        // TODO add your handling code here:
//        doubleClick_table();
        int row = tbl_resultado.getSelectedRow(); //.rowAtPoint(evt.getPoint());
        int col = tbl_resultado.getSelectedColumn(); //.columnAtPoint(evt.getPoint());
        int clicks = evt.getClickCount();
        if (clicks == 2) {
            JOptionPane.showMessageDialog(null, "Clicou DUAS vezes!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
//        }else{
//            JOptionPane.showMessageDialog(null, "Clicou "+clicks+" vezes!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
//        }
//        if (row >= 0 && col >= 0) {
//            JOptionPane.showMessageDialog(null, "Linha " + (row+1) + ", Coluna " + (col+1) + ".", "Atenção", JOptionPane.INFORMATION_MESSAGE);
//        }

    }//GEN-LAST:event_tbl_resultadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_pesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_grp_criterio;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_criterio;
    private javax.swing.JPanel pnl_pesquisa;
    private javax.swing.JRadioButton rad_ator;
    private javax.swing.JRadioButton rad_filme;
    private javax.swing.JTable tbl_resultado;
    private javax.swing.JTextField txt_criterio;
    // End of variables declaration//GEN-END:variables
}
