/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author alex
 */
public class Frm_main extends javax.swing.JFrame {

    /**
     * Creates new form Frm_main
     */
    public Frm_main() {
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            initComponents();

            getContentPane().setBackground(Color.darkGray);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Frm_main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Frm_main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Frm_main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Frm_main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_pesquisa_imdb = new javax.swing.JButton();
        btn_gere_bd = new javax.swing.JButton();
        btn_about = new javax.swing.JButton();
        btn_pesquisa_bd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlDkShadow);
        setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        btn_pesquisa_imdb.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        btn_pesquisa_imdb.setText("Pesquisar no IMDB");
        btn_pesquisa_imdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_imdbActionPerformed(evt);
            }
        });

        btn_gere_bd.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        btn_gere_bd.setText("Gerir Banco de Dados");
        btn_gere_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gere_bdActionPerformed(evt);
            }
        });

        btn_about.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        btn_about.setText("About");
        btn_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutActionPerformed(evt);
            }
        });

        btn_pesquisa_bd.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        btn_pesquisa_bd.setLabel("Listar Atores");
        btn_pesquisa_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_bdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 100)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.info);
        jLabel1.setText("Scrapper");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 100)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.activeCaption);
        jLabel2.setText("IMDB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_pesquisa_bd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pesquisa_imdb, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_gere_bd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pesquisa_imdb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gere_bd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pesquisa_bd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_about, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisa_imdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_imdbActionPerformed
        // TODO add your handling code here:
        Frm_pesquisa frm_run = new Frm_pesquisa(this);
        frm_run.setLocationRelativeTo(null);
        frm_run.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_pesquisa_imdbActionPerformed

    private void btn_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "<html><center><font color=#000055><b>IMDB </font><font color=#FFFF00>Scraper</b></font></html>"
                + "\n\n<html><b>Desenvolvedor:</b> Alex Almeida</html>"
                + "\n<html><b>Contato:</b> alex.aldr@gmail.com</html>"
                + "\n<html><b>Telefone:</b> (38) 98829-3376</html>",
                "About IMDB Scraper", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_aboutActionPerformed

    private void btn_pesquisa_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_bdActionPerformed
        Frm_lista frm_run = new Frm_lista(this);
        frm_run.setLocationRelativeTo(null);
        frm_run.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_pesquisa_bdActionPerformed

    private void btn_gere_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gere_bdActionPerformed
        Frm_gerencia frm_run = new Frm_gerencia(this);
        frm_run.setLocationRelativeTo(null);
        frm_run.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_gere_bdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frm_main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_about;
    private javax.swing.JButton btn_gere_bd;
    private javax.swing.JButton btn_pesquisa_bd;
    private javax.swing.JButton btn_pesquisa_imdb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
